def rules_displacement(j):
    """ Displacement Key """
    s = [
        j.replace("گ", "ک"),
        j.replace("ک", "گ"),
        j.replace("ک", "م"),
        j.replace("م", "ک"),
        j.replace("م", "ن"),
        j.replace("ن", "م"),
        j.replace("ن", "ت"),
        j.replace("ت", "ن"),
        j.replace("ت", "ا"),
        j.replace("ا", "ت"),
        j.replace("ا", "ل"),
        j.replace("ل", "ا"),
        j.replace("ل", "ب"),
        j.replace("ب", "ل"),
        j.replace("ب", "ی"),
        j.replace("ی", "ب"),
        j.replace("ی", "س"),
        j.replace("س", "ی"),
        j.replace("س", "ش"),
        j.replace("ش", "س"),
        j.replace("پ", "چ"),
        j.replace("چ", "پ"),
        j.replace("چ", "ج"),
        j.replace("ج", "چ"),
        j.replace("ج", "ح"),
        j.replace("ح", "ج"),
        j.replace("ح", "خ"),
        j.replace("خ", "ح"),
        j.replace("خ", "ه"),
        j.replace("ه", "خ"),
        j.replace("ه", "ع"),
        j.replace("ع", "ه"),
        j.replace("ع", "غ"),
        j.replace("غ", "ع"),
        j.replace("غ", "ف"),
        j.replace("ف", "غ"),
        j.replace("ف", "ق"),
        j.replace("ق", "ف"),
        j.replace("ق", "ث"),
        j.replace("ث", "ق"),
        j.replace("ث", "ص"),
        j.replace("ص", "ث"),
        j.replace("ص", "ض"),
        j.replace("ض", "ص"),
        j.replace("و", "ئ"),
        j.replace("ئ", "و"),
        j.replace("ئ", "د"),
        j.replace("د", "ئ"),
        j.replace("د", "ذ"),
        j.replace("ذ", "د"),
        j.replace("ذ", "ر"),
        j.replace("ر", "ذ"),
        j.replace("ر", "ز"),
        j.replace("ز", "ر"),
        j.replace("ز", "ط"),
        j.replace("ط", "ز"),
        j.replace("ط", "ظ"),
        j.replace("ظ", "ط")
    ]
    unique_list = []
    # unique_list.append('(')
    for x in s:
        # check if exists in unique_list or not
        if x not in unique_list:
            unique_list.append(x)
    return unique_list
